version: '3.8'

services:
  web:
    build: .
    container_name: supplies_web
    restart: unless-stopped
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - "8002:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
