# Generated by Django 6.0.6 on 2026-06-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название расходника')),
                ('part_number', models.CharField(help_text='Оригинальный партномер производителя', max_length=100, unique=True, verbose_name='Партномер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='consumable_photos/', verbose_name='Фото расходника')),
            ],
            options={
                'verbose_name': 'Расходный материал',
                'verbose_name_plural': 'Расходные материалы',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вендора')),
            ],
            options={
                'verbose_name': 'Вендор',
                'verbose_name_plural': 'Вендоры',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Модель')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='device_photos/', verbose_name='Фото устройства')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='supplies_app.devicetype', verbose_name='Тип устройства')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='supplies_app.vendor', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='supplies_app.consumable', verbose_name='Расходник')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='supplies_app.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Совместимость',
                'verbose_name_plural': 'Совместимости',
                'unique_together': {('device', 'consumable')},
            },
        ),
    ]
