# Generated by Django 6.0.6 on 2026-07-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AddField(
            model_name='consumable',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='supplies_app.vendor', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='compatibility',
            name='consumable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='supplies_app.consumable', verbose_name='Расходный материал'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название расходного материала'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='part_number',
            field=models.CharField(help_text='Оригинальный номер производителя', max_length=100, unique=True, verbose_name='Артикул производителя'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='consumable_photos/', verbose_name='Фото расходного материала'),
        ),
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='supplies_app.vendor', verbose_name='Производитель'),
        ),
    ]
