# Generated by Django 6.0.6 on 2026-07-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_app', '0002_alter_vendor_options_consumable_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип расходника',
                'verbose_name_plural': 'Типы расходников',
            },
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название производителя'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='consumable_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='supplies_app.consumabletype', verbose_name='Тип расходника'),
        ),
    ]
