# Generated by Django 6.0.6 on 2026-07-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_app', '0003_consumabletype_alter_vendor_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(blank=True, help_text='Заполняется автоматически из производителя, типа, цвета и артикула', max_length=200, verbose_name='Название расходного материала'),
        ),
        migrations.AddField(
            model_name='consumable',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumables', to='supplies_app.color', verbose_name='Цвет'),
        ),
    ]
